language: python
install:
  - pip install tox
  - pip install pyflakes
services:
  - redis-server
notifications:
  email:
    recipients:
    - justin@justinholmes.com
    on_success: change
    on_failure: always
script: tox
before_install:
  - pip install codecov
after_success:
  - codecov